name: AEnv Images Build and Push

on:
  workflow_dispatch:

env:
  REGISTRY: aenvironment

jobs:
  build-aenvironemnt-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract metadata for api-service
        id: meta_api_service
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/api-service
          tags: &common-tags |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha

      - name: Extract metadata for envhub
        id: meta_envhub
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/envhub
          tags: *common-tags

      - name: Extract metadata for controller
        id: meta_controller
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/controller
          tags: *common-tags

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./api-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_api_service.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push api-service image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./api-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_api_service.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push env-hub image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./envhub/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_envhub.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push controller image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./controller/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_controller.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max