name: Release AEnvironment SDK

on:
  push:
    branches:
      - add_workflow
    paths:
      - '.github/workflows/release_pypi_task.yml'
  workflow_dispatch:

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build setuptools wheel

      - name: Build package
        run: |
          cd ./aenv
          python scripts/build_version.py
          python -m build    

      - name: Move dist to workspace and Verify wheel metadata test
        run: |
          mv ./aenv/dist .
          unzip -p dist/*.whl METADATA | grep "Requires-Dist" || echo "WARNING: No dependencies found!"

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_AUTH_PASSWORD }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_AUTH_PASSWORD }}