name: Envs BuiltIn Images Build and Push Trigger3

on:
  push:
    branches:
      - buildin_envs
    paths:
      - '.github/workflows/sample_env_image_build.yml'
  workflow_dispatch:

env:
  NAMESPACE: aenvironment

jobs:
  build-aenvironemnt-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract metadata for mini-terminal
        id: meta_mini_terminal
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.NAMESPACE }}/mini-terminal
          tags: &common-tags |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Extract metadata for tau2
        id: meta_tau2
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.NAMESPACE }}/tau2
          tags: *common-tags

      - name: Extract metadata for terminalbench
        id: meta_tb
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.NAMESPACE }}/terminalbench
          tags: *common-tags


      - name: Build and push mini-terminal image
        uses: docker/build-push-action@v5
        with:
          context: ./aenv/builtin-envs/mini-terminal
          file: ./aenv/builtin-envs/mini-terminal/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_mini_terminal.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push tau2 image
        uses: docker/build-push-action@v5
        with:
          context: ./aenv/builtin-envs/tau2
          file: ./aenv/builtin-envs/tau2/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_tau2.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push terminalbench image
        uses: docker/build-push-action@v6
        with:
          context: ./aenv/builtin-envs/terminalbench
          file: ./aenv/builtin-envs/terminalbench/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_tb.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max